dbt_project:
  outputs:
    dev:
      account: SYOPAVH-ZZ37525
      database: dbt_db
      password: 
      role: accountadmin
      schema: source
      threads: 1
      type: snowflake
      user: ashoksnow
      warehouse: compute_wh
    prod:
      account: SYOPAVH-ZZ37525
      database: dbt_db_prod
      password: 
      role: accountadmin
      schema: source
      threads: 1
      type: snowflake
      user: ashoksnow
      warehouse: compute_wh
  target: dev
